Rename history.js to historyConfig.js
Error: "createBrowserHistory is not exported from history.js file" -- resolved. 
There was this conflict between actual history package and the history.js file. Renaming the history.js file to @history.js or anything else solves the issue.